### ISSUE TITLE
Recurring support for OpenCart

### ISSUE THREAD

**Issue by timarmatyas** [paylike/plugin-opencart-3#14]
Dear Developer,

We would like use Recurring Payment Profiles in OpenCart, as soon as possible. Do you can can implement that function for us? We use OC 3.0.3.3

Greetings,
Matyas Timar

**Comment by ionutcalara** [comment]
Our team is looking into this and we'll get back to you with an answer, and if feasible with a timeline.

**Comment by timarmatyas** [comment]
Thank you! About when can I expect an answer?

**Comment by timarmatyas** [comment]
Dear Developer, Do you have any news for me? Thank you!

**Comment by ionutcalara** [comment]
Hi, @timarmatyas I apologize for the delay. Since we didn't found what we needed, it took longer to figure out if this is feasible. Unfortunately, due to the fact that opencart does not have an internal subscription implementation, and the subscription is only left to the payment to handle including a lot of aspects that require tracking the timeline and notifying and generating payment links for the user, it's not possible for us to easily provide subscription functionality for open cart. 

We might integrate in the future, but for now, this will not be supported. 

Currently, the only module that supports subscriptions is the WooCommerce module for Paylike.

**Comment by timarmatyas** [comment]
Dear @ionutcalara,

Thank you! Yor wrote: "opencart does not have an internal subscription implementation" ...but what is Recurring Profile? http://docs.opencart.com/en-gb/sale/recurring/

**Comment by ionutcalara** [comment]
Hi @timarmatyas, after analyzing the profiles, these are merely storing data, but opencart leaves the part about setting a certain subscription renewal date, handling changes in terms of charge period/ upgrades/downgrades, etc to the payment modules. This is not something strictly related to payment, as all subscriptions no matter what payment the user uses should work the same. 

However, open cart does not implement that logic and leaves it to the payment providers or third party plugins. This makes it complicated as there are a lot of situations the payment module would have to handle, without the access the framework has, so it's not simple and it leaves a lot of room for issues that each module would handle, instead of open cart handling it for all of them. 

So to answer your questions, the recurring profile, is just a "profile" it holds and displays data, but doesn't act in any way other  than that. So it's not a subscription system, is just the data structure for it.

**Comment by timarmatyas** [comment]
Thank you for your help!
